/**
 * Permission actions contributed by the masterData module.
 *
 * Each string is the camelCase form of a backend permission key in
 * `helper/Permission/PermissionList.php` — `'see:campus'` → `'seeCampus'`.
 * `allowedRoutesStore.can(...)` and the `$can` template global only accept
 * members of this union, so a typo fails type-check instead of silently
 * hiding a button.
 */
export type MasterDataAllowedAction =
    | 'seeCampus'
    | 'createCampus'
    | 'updateCampus'
    | 'deleteCampus'
    | 'changeCampusState'
    | 'seeBuilding'
    | 'createBuilding'
    | 'updateBuilding'
    | 'deleteBuilding'
    | 'changeBuildingState'
    | 'seeCollege'
    | 'createCollege'
    | 'updateCollege'
    | 'deleteCollege'
    | 'changeCollegeState'
    | 'seeDepartment'
    | 'createDepartment'
    | 'updateDepartment'
    | 'deleteDepartment'
    | 'changeDepartmentState'
    | 'seeAcademicYear'
    | 'createAcademicYear'
    | 'updateAcademicYear'
    | 'deleteAcademicYear'
    | 'seeProgram'
    | 'createProgram'
    | 'updateProgram'
    | 'deleteProgram'
    | 'changeProgramState'
    | 'seeSemester'
    | 'createSemester'
    | 'updateSemester'
    | 'deleteSemester'
    | 'changeSemesterStatus'
    | 'seeSection'
    | 'createSection'
    | 'updateSection'
    | 'deleteSection'
    | 'changeSectionState'
    | 'seeRoom'
    | 'createRoom'
    | 'updateRoom'
    | 'deleteRoom'
    | 'changeRoomState'
    | 'seeCourse'
    | 'createCourse'
    | 'updateCourse'
    | 'deleteCourse'
    | 'changeCourseState'
    | 'seeInstructor'
    | 'createInstructor'
    | 'updateInstructor'
    | 'deleteInstructor'
    | 'changeInstructorState';
