<script setup lang="ts">
import { watch } from 'vue';

import MainDialog from '@/components/common/MainDialog.vue';
import InputText from '@/components/common/InputText.vue';
import MainButton from '@/components/common/MainButton.vue';
import MainSelect from '@/components/common/MainSelect.vue';
import CheckBox from '@/components/common/CheckBox.vue';
import FieldWrapper from '@/components/wrapper/FieldWrapper.vue';
import type { PermissionForm, PermissionGroup } from '@/modules/user/types/AccessManagement/permission';

const props = defineProps<{
    visible: boolean;
    isEditing: boolean;
    isSaving: boolean;
    form: PermissionForm;
    errors: Record<string, string>;
    groups: PermissionGroup[];
    modules: { id: number; name: string }[];
}>();

const emit = defineEmits<{
    (e: 'update:visible', val: boolean): void;
    (e: 'save'): void;
}>();

const slugify = (text: string): string =>
    (text || '')
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, ' ')
        .trim()
        .split(/\s+/)
        .filter(Boolean)
        .join(':');

watch(
    () => props.form.name,
    (name) => {
        if (!props.isEditing) {
            props.form.key = slugify(name);
        }
    }
);
</script>

<template>
    <MainDialog
        :no-x-padding="true"
        :plain-background="true"
        :visible="visible"
        :header="isEditing ? $lang.editPermission : $lang.createPermission"
        max-width="max-w-2xl"
        @update:visible="emit('update:visible', $event)">
        <div class="mx-4 space-y-5 py-1">
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div :class="isEditing ? 'sm:col-span-2' : ''">
                    <InputText
                        v-model="form.name"
                        :label="$lang.name || 'Name'"
                        :placeholder="$lang.enterName || 'Enter name'"
                        :invalid="!!errors.name"
                        :message="errors.name"
                        message-type="error" />
                </div>

                <div v-if="!isEditing">
                    <label class="text-text-secondary mb-1 block text-sm font-medium">{{ $lang.key || 'Key' }}</label>
                    <InputText
                        :model-value="form.key"
                        :disabled="true"
                        :placeholder="$lang.autoGeneratedFromName || 'Auto-generated from name'"
                        :invalid="!!errors.key"
                        :message="errors.key"
                        message-type="error" />
                    <p class="text-text-tertiary mt-1 text-xs">
                        {{ $lang.keyAutoGeneratedHelp || 'Generated automatically from the name.' }}
                    </p>
                </div>
            </div>

            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <FieldWrapper :label="$lang.module || 'Module'">
                    <MainSelect
                        v-model="form.module_id"
                        :options="modules"
                        option-label="name"
                        option-value="id"
                        :placeholder="$lang.selectModule || 'Select module'"
                        :invalid="!!errors.module_id" />
                    <p
                        v-if="errors.module_id"
                        class="text-schedule-error-default mt-1 text-xs">
                        {{ errors.module_id }}
                    </p>
                </FieldWrapper>

                <FieldWrapper :label="$lang.permissionGroup || 'Permission Group'">
                    <MainSelect
                        v-model="form.permission_group_id"
                        :options="groups.map((g) => ({ id: g.id, name: g.name }))"
                        option-label="name"
                        option-value="id"
                        :disabled="!form.module_id"
                        :placeholder="
                            form.module_id
                                ? $lang.selectPermissionGroup || 'Select group'
                                : $lang.selectModuleFirst || 'Select a module first'
                        "
                        :invalid="!!errors.permission_group_id" />
                    <p
                        v-if="errors.permission_group_id"
                        class="text-schedule-error-default mt-1 text-xs">
                        {{ errors.permission_group_id }}
                    </p>
                </FieldWrapper>
            </div>

            <div class="border-border-subtle space-y-3 border-t pt-5">
                <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    <label
                        class="border-border-subtle hover:border-schedule-brand-blue/40 flex cursor-pointer items-center gap-3 rounded-xl border p-3 transition-colors">
                        <CheckBox
                            v-model="form.unique_per_user"
                            :binary="true" />
                        <span class="text-text-primary text-sm font-medium">
                            {{ $lang.uniquePerUser || 'Unique Per User' }}
                        </span>
                    </label>
                </div>
            </div>
        </div>

        <template #footer>
            <div class="mx-2 flex items-center justify-end gap-3">
                <MainButton
                    outlined
                    :label="$lang.cancel || 'Cancel'"
                    @click="emit('update:visible', false)" />
                <MainButton
                    :label="isEditing ? $lang.saveChanges || 'Save Changes' : $lang.save || 'Save'"
                    severity="primary"
                    :loading="isSaving"
                    @click="emit('save')" />
            </div>
        </template>
    </MainDialog>
</template>
